policy:
  approval:
    - only-fvgtekken-on-develop

approval_rules:
  - name: only-fvgtekken-on-develop
    if:
      targets_branch:
        pattern: '^develop$'
    options:
      allow_author: true
      allow_contributor: true
      invalidate_on_push: true

    requires:
      count: 1
      users: ['fvgtekken']
